@startmindmap

* 可信计算环境
** APP
** Enclave
*** 项目信息
*** 分账信息
*** 卡域信息
*** 订单信息
*** 项目资产信息
*** 账单管理
*** 账单支付管理

** SGX服务代理(Java)
*** 回调接口restful转tcp
*** 银联支付(加密，签名，验签)
*** 银联支付请求(服务器SSL信任问题Rust不能解决)

*** 定时任务
**** 从中台转移相关数据到SGX
**** 定时发起后台分账
**** 定时刷新分账交易状态(未完成的交易)
**** 定时迁移数据到中台(账单分账记录，账单状态)

@endmindmap
