@startmindmap
* 增加收入
** 主动收入
*** 网约车
*** 其他兼职

** 被动收入
*** 证书GK
*** 投资类
**** 固定资产：房产、商铺
**** 基金、股票、期货、黄金、存款
**** 保险

*** 知识产权类
**** 电子书
**** 视频类
***** 抖音、火山等
***** Youtube频道
**** 自媒体(需要积累知识)

*** 联盟营销
**** 谷歌联盟
**** 百度联盟
**** 淘宝客、花生日记

*** 试玩挂机类
**** APP试玩
**** 微信挂机

@endmindmap