spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/data_platform_iot?characterEncoding=utf8&useSSL=false&autoReconnect=true&failOver
    username: root
    password: Energy@123456
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 127.0.0.1
    database: 15
server:
  port: 8085
  sgx:
    host: 127.0.0.1
    port: 3443
    cert:
      algorithm: EC
      certificate: classpath:/resources/cert/client.crt
      private-key: classpath:/resources/cert/client.pkcs8
      ca-file: classpath:/resources/cert/AttestationReportSigningCACert.pem
      output: classpath:/resources/cert
logging:
  level:
    root: INFO
swagger:
  enabled: true
  title: "SGX Client API"
#  global-operation-parameters:
#    - { name: "token", description: "token", modelRef: "string", parameterType: "header", required: false}
